version: '3'

services:
  api:
    build:
      context: ./flask_api
      args:
        FLASK_ENV: ${FLASK_ENV}
    ports:
      - "5000:5000"
    env_file:
      - ./flask_api/.env  # Specify the local environment file
      - ./flask_api/.env.prod  # Specify the production environment file
    volumes:
      - ./flask_api:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
