
services:
  api:
    build:
      context: ./flask_api
      args:
        FLASK_ENV: development
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    env_file:
      - ./flask_api/.env  # Specify the local environment file
    volumes:
      - ./flask_api:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Optional: expose port if you need external access
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
  
  frontend:
    build: 
      context: ./react_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./react_frontend:/app
      - /app/node_modules
    command: sh -c "echo NODE_ENV=$NODE_ENV && npm run start"
volumes:
  postgres_data:
