
services:
  api:
    build:
      context: ./flask_api
      args:
        FLASK_ENV: production
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    env_file:
      - ./flask_api/.env.prod # Specify the local environment file
    volumes:
      - ./flask_api:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - ./flask_api/.env.prod # Specify the local environment file for db as well
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST_RDS}
      POSTGRES_PORT: ${POSTGRES_PORT}
  frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_ADDRES = 16.171.173.218:5000/api
    ports:
      - "80:80"  # Serve on port 80 for production
    volumes:
      - ./react_frontend/build:/usr/share/nginx/html  # Serve static files
