"""My tables

Revision ID: 259a6c33a3ae
Revises: 
Create Date: 2024-07-28 20:47:54.874155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259a6c33a3ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_text', sa.Text(), nullable=False),
    sa.Column('additional_instructions', sa.Text(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('assistant_scenarios')
    # ### end Alembic commands ###
