"""Update Assistant Table

Revision ID: 30983e40068e
Revises: c93b7e74d92a
Create Date: 2024-07-31 12:11:26.254874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30983e40068e'
down_revision = 'c93b7e74d92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('openid', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.drop_column('openid')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
